### ISSUE TITLE
move documents into sub-directory

### ISSUE THREAD

**Issue by inoueakimitsu** [inoueakimitsu/milwrap#17]
```yaml
start_date: 2022/8/29
due_date: 2022/8/29
progress: 0.1
parent: 0
```
Move technical reports into the sub-directory.
